Add ValidateFunc to resc TFE_Project name
hashicorp/terraform-provider-tfe pull request #1093
Opened 2023-10-07 19:12 UTC by isaacmcollins

## Description

Added TFE Project name validation to check for length and allowed characters at plan stage. The API docs specify a Project name can only include letters, numbers, spaces, -, and _. It must be at least 3 characters long and no more than 36 characters long.

Closes #1043 

## Testing plan
 ```TESTARGS="-run TestAccTFEProject_invalidName" make testacc```

## Output from acceptance tests
```
% TESTARGS="-run TestAccTFEProject_invalidName" make testacc 
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEProject_invalidName -timeout 15m
?       github.com/hashicorp/terraform-provider-tfe     [no test files]
=== RUN   TestAccTFEProject_invalidName
--- PASS: TestAccTFEProject_invalidName (1.08s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/provider   3.375s
?       github.com/hashicorp/terraform-provider-tfe/version     [no test files]
```

2023-10-11 23:25 UTC, nfagerlund requested changes
Thanks for submitting this! It'll be nice to get an early warning at plan-time if there's a name problem. 

One request: If we're gonna do this, let's go ahead and include all the API's restrictions! It's left unsaid in the API docs, but TFC also disallows leading and trailing spaces in project names.

Once that's tweaked, I'll nudge the CI system to allow the tests to pass, and we can get this in.

2023-10-11 23:25 UTC, nfagerlund commented on internal/provider/resource_tfe_project.go
> +					validation.StringMatch(regexp.MustCompile(`\A[\w\_\- ]+\z`),
This is that regexp adjustment — excluding space from the first and last character classes. (Also, underscores are included in \w, so they don't need to be explicitly added to the class.)

```suggestion
					validation.StringMatch(regexp.MustCompile(`\A[\w\-][\w\- ]+[\w\-]\z`),
```

2023-10-15 18:46 UTC, isaacmcollins commented
> Thanks for submitting this! It'll be nice to get an early warning at plan-time if there's a name problem.
> 
> One request: If we're gonna do this, let's go ahead and include all the API's restrictions! It's left unsaid in the API docs, but TFC also disallows leading and trailing spaces in project names.
> 
> Once that's tweaked, I'll nudge the CI system to allow the tests to pass, and we can get this in.

Added, thanks for the help!

2023-10-25 00:35 UTC, nfagerlund approved these changes
All right! Looks good, and tests are passing 👍🏼

2023-10-25 00:35 UTC, merged