Add project level auto destroy
hashicorp/terraform-provider-tfe pull request #1550
Opened 2024-12-19 20:29 UTC by simonxmh

## Description

Add support in the tfe provider for the project level ephemeral workspace settings.

_Remember to:_

- [ ] _Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md)_
- [ ] _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md#updating-the-documentation)_

## Testing plan

1.  _Describe how to replicate_
1.  _the conditions_
1.  _under which your code performs its purpose,_
1.  _including example Terraform configs where necessary._

## External links

_Include any links here that might be helpful for people reviewing your PR. If there are none, feel free to delete this section._

- [go-tfe documentation](https://pkg.go.dev/github.com/hashicorp/go-tfe?tab=doc#xxxx)
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs/xxxx)
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/xxxx)

## Output from acceptance tests

_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/testing.md) to learn how to run acceptance tests._

_If you are an external contributor, your contribution(s) will first be reviewed before running them against the project's CI pipeline._

```
$ TESTARGS="-run TestAccTFEWorkspace" make testacc

...
```

2025-01-03 16:01 UTC, notchairmk commented on go.mod
> +replace github.com/hashicorp/go-tfe => ../go-tfe
Instead of this, you should update go.mod to reference your newest commit `98975f447700482a79e4d7d177cd406ff8132f1d` from go-tfe so we can see tests running and stuff

2025-01-04 00:34 UTC, notchairmk commented on internal/provider/resource_tfe_workspace_test.go
> +	resource.Test(t, resource.TestCase{
just FYI this test is failing for me because it's trying to remove the project when the workspace is still attached
```
resource_tfe_workspace_test.go:2841: Step 3/4 error: Error running apply: exit status 1

Error: Error deleting project prj-UsNktA5H5kR7mfYB: invalid attribute
```

2025-01-06 17:53 UTC, simonxmh commented on go.mod
> +replace github.com/hashicorp/go-tfe => ../go-tfe
That's helpful! I was waiting for the release but this makes sense

2025-01-07 18:00 UTC, simonxmh commented on internal/provider/resource_tfe_workspace_test.go
> +	resource.Test(t, resource.TestCase{
This should be fixed, there was a step in there with a workspace outside the projects

2025-01-24 20:10 UTC, notchairmk commented on CHANGELOG.md
> +* `d/tfe_project`: Add `auto_destroy_activity_duration` field to the project datasource [1550](https://github.com/hashicorp/terraform-provider-tfe/pull/1550)
these should go in the unreleased, I think they may have got pulled into v0.63.0 when merging main

2025-01-24 20:11 UTC, notchairmk commented on go.mod
> +	github.com/stretchr/testify v1.10.0
do we need to upgrade testify as part of these changes?

2025-01-27 17:05 UTC, simonxmh commented on CHANGELOG.md
> +* `d/tfe_project`: Add `auto_destroy_activity_duration` field to the project datasource [1550](https://github.com/hashicorp/terraform-provider-tfe/pull/1550)
I fixed it, it was indeed merged into main.

2025-01-27 17:05 UTC, simonxmh commented on go.mod
> +	github.com/stretchr/testify v1.10.0
I think it was unintentionally merged in with a newer version of go-tfe earlier. I reverted this.

2025-01-27 23:12 UTC, emailnitram approved these changes
tested provider locally and looks good

2025-01-28 00:41 UTC, emailnitram submitted a review, later dismissed

2025-01-28 19:44 UTC, notchairmk commented
Just tried this out, it looks like removing an `auto_destroy_at` override from a workspace that's in a project with an auto destroy duration defined doesn't work.

2025-01-28 22:47 UTC, simonxmh commented
> Just tried this out, it looks like removing an `auto_destroy_at` override from a workspace that's in a project with an auto destroy duration defined doesn't work.

Will sync with you on this. Cannot replicate this at the moment.

2025-01-29 22:48 UTC, notchairmk commented on internal/provider/resource_tfe_workspace.go
> +		d.Set("auto_destroy_activity_duration", nil)
very minor nit, imitating the logic above for other nilable strings (and what we do in the project data source) would probably be better

```go
		var autoDestroyDuration string
		if proj.AutoDestroyActivityDuration.IsSpecified() {
			autoDestroyDuration, err = proj.AutoDestroyActivityDuration.Get()
			if err != nil {
				return diag.Errorf("Error reading auto destroy activity duration: %v", err)
			}
		}
```

2025-01-29 22:48 UTC, notchairmk submitted a review, later dismissed
Thanks, looks good! 🚢

2025-01-30 22:50 UTC, sebasslash requested changes
Implementation is looking good. We're missing the doc changes for `r/tfe_project` however

2025-02-03 15:35 UTC, simonxmh commented on internal/provider/data_source_project_test.go
> +	rInt := rand.New(rand.NewSource(time.Now().UnixNano())).Int()
I'll use `skipIfEnterprise` if that's the flag you mean? I don't believe `skipUnlessCloud` is a thing. Unless you mean the opposite?

2025-02-03 15:42 UTC, simonxmh commented
> Implementation is looking good. We're missing the doc changes for `r/tfe_project`, `r/tfe_workspace` and `d/tfe_workspace` however

I added the docs for `r/tfe_project`,and `d/tfe_workspace`, but not for `r/tfe_workspace` because the interface didn't really change for the resource. The `inherits_project_auto_destroy` attribute is also read-only so not a configuring attribute.

2025-02-03 20:38 UTC, sebasslash approved these changes

2025-02-03 21:05 UTC, merged