Adds description parameter to TFE Workspace
hashicorp/terraform-provider-tfe pull request #271
Opened 2021-02-16 16:50 UTC by petems

* Requires go-tfe update

## Description

Adds description to workspace 

## External links

_Include any links here that might be helpful for people reviewing your PR. If there are none, feel free to delete this section._

- https://github.com/hashicorp/go-tfe/issues/170

https://www.terraform.io/docs/cloud/api/workspaces.html#request-body

data.attributes.description | string | (nothing) | A description for the workspace.
-- | -- | -- | --

Required in create and read

2021-02-16 16:54 UTC, chrisarcand requested changes
* Needs some test additions 💞 
* Run a `go mod tidy` to remove the 0.12.0 refs, too.

2021-02-16 16:54 UTC, chrisarcand commented on tfe/resource_tfe_workspace.go
> +				Default:  false,
`false`? I think you want `""` here.

2021-03-06 08:00 UTC, petems commented on tfe/resource_tfe_workspace.go
> +				Default:  false,
Fixed! 👍

2021-03-06 08:00 UTC, petems commented
@chrisarcand Added tests 🖖

2021-03-16 15:24 UTC, chrisarcand requested changes
Hey! Sorry for the delay.

2021-03-16 15:24 UTC, chrisarcand commented on tfe/data_source_workspace_test.go
> +  description						= "provider-testing"
```suggestion
  description           = "provider-testing"
```

2021-03-16 15:24 UTC, chrisarcand commented on tfe/resource_tfe_workspace.go
> +				Default:  "",
Sorry, I know we already changed this from `false` before....I don't believe this is necessary at all, right? Descriptions can be `null`; the zero value of the field here will naturally be `""` anyway.

2021-03-16 15:24 UTC, chrisarcand commented on tfe/resource_tfe_workspace_test.go
> +
I don't think this simple field merits a separate expensive test; let's move it in to `TestAccTFEWorkspace_basic` with other basic arguments.

2021-04-20 01:24 UTC, chrisarcand approved these changes

2021-04-20 01:24 UTC, merged