Fixing plugin crash when providing empty strings to argument
hashicorp/terraform-provider-tfe pull request #421
Opened 2022-01-24 19:19 UTC by sebasslash

## Description

This is a really simple fix that closes #409 by preventing the user to set the `names` argument for `tfe_data_source_workspace_ids` to an array of empty strings or an array that contains empty strings. The reason for this is the plugin sdk fetches empty strings as `nil` values, causing any type casting operations to panic. 

There is an alternative up for discussion, let's say the user provides `["wkspace1", "", "wkspace2"]`, should the plugin read this as `["wkspace1", "wkspace2"]` omitting any entries that are `nil`? This might be a better alternative as `[]` is a valid assignment and therefore omitting entries that are nil (in a case where all entries are nil) would effectively be the same as `[]`.

## Testing plan

1.  In order to test ensure you have your provider overrides setup, and have an available Terraform configuration to test with
2. Create a data source block and apply:
```hcl
data "tfe_workspace_ids" "this" {
  names = [""],
  organization = "your-org-here"
}
```
3. You should receive an error that states: `names argument cannot have empty strings`

2022-01-24 20:12 UTC, barrettclark requested changes
Can you add this case to the tests? I also noticed there is a test failure, which may just be a flickering test failure.

2022-01-24 21:52 UTC, sebasslash commented
Yeah looks like a flickering test, ran the failed tests locally and they passed.

2022-01-25 02:01 UTC, brandonc commented
That is a new test we should probably keep an eye on it.

2022-01-25 15:13 UTC, barrettclark approved these changes

2022-01-25 15:49 UTC, merged