Add run_tasks permission to Team Access
hashicorp/terraform-provider-tfe pull request #487
Opened 2022-05-05 06:48 UTC by glennsarti

# This is blocked on go-tfe v1.2 being released and updated in this project.

## Description

Run Tasks has added a new `run_tasks` custom permission to Team
Workspace access.  This commit adds this new permission to the
Team Access object (both resource and data) and adds acceptance
tests for both objects.

## Testing plan

N/A  Added acceptance tests

## External links

- [go-tfe documentation](https://github.com/hashicorp/go-tfe/blob/main/team_access.go#L101

## Output from acceptance tests

N/A It'll be in the CI tests

2022-05-05 06:50 UTC, glennsarti commented
This is a breaking change because custom access permissions will _require_ the run_tasks parameter

e.g.

```
resource "tfe_team_access" "foobar" {
  permissions {
    runs = "apply"
    variables = "read"
    state_versions = "read-outputs"
    sentinel_mocks = "none"
    workspace_locking = false
    run_tasks = false           <------ THIS IS NOW REQUIRED
  }
 ```

2022-06-13 16:43 UTC, sebasslash requested changes
Code looks good, missing the provider documentation + Wondering how our docs should reflect this breaking change? Would a simple `-> **Note**` suffice?

2022-06-16 03:37 UTC, glennsarti commented
@sebasslash   I've updated the docs and changelog. I have no idea how to surface the breaking changen-ess besides bumping a major version number.

2022-06-16 15:16 UTC, brandonc commented
@glennsarti I think we reserve the right to break the API in reasonable ways until release 1.0. The best thing to do is just note it in CHANGELOG, as you've done.

I've already forgotten why we couldn't default this setting, but I'm wondering how to avoid similar breaking changes after 1.0...

2022-06-16 15:18 UTC, brandonc approved these changes

2022-06-17 01:27 UTC, glennsarti commented
For ref - Private chat about why it is - https://hashicorp.slack.com/archives/C01BR9FR8KZ/p1651525482312299

> The problem therein lies: access and permissions behave both as arguments and computed properties, but their behavior depends on whether the other is marked as an argument or as a computed property. The reason for this weird behavior is due to the [Team Access API](https://www.terraform.io/cloud-docs/api-docs/team-access#add-team-access-to-a-workspace): you cannot set custom permissions unless the access field is set to custom so we can't treat both attributes as arguments because if permissions is set, access is computed to "custom" and if access is set, permissions is computed to whatever values are returned by the API.
Setting default values however breaks this behavior because the intent is muddled, are we using access to set the permissions or the default values of permissions ?

2022-06-17 01:28 UTC, glennsarti commented
@sebasslash Re-requesting a review based on the changes I made.

2022-06-17 17:13 UTC, brandonc approved these changes
@sebasslash is out of the office but I think we are good to go. Thanks for adding context about the required permission arguments!

2022-06-20 00:51 UTC, merged