Change default for `file_triggers_enabled` to false
hashicorp/terraform-provider-tfe pull request #510
Opened 2022-06-02 09:31 UTC by matejrisek

## Description

Change default for `file_triggers_enabled` to false.

Why?
Current default is wrong and we're having a clause on [the Atlas side](https://github.com/hashicorp/atlas/blob/main/app/models/workspace.rb#L339) to account for this behavior.
New trigger types, e.g. tag based triggering, will depend on this field being set to `false`. We'll introduce the conflict between the new fields and `file_triggers_enabled`.

_Remember to:_

- _Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/README.md#updating-the-changelog)_

- _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/README.md#updating-the-documentation)_

## Testing plan

1. Define a new workspace without `file_triggers_enabled`
2. Newly created workspace should have the field set to `false`

2022-06-02 10:38 UTC, omarismail commented
@matejrisek Any reason to wait on updating the documentation in this PR

2022-06-02 15:25 UTC, annawinkler approved these changes
🚀

2022-06-02 15:49 UTC, brandonc approved these changes

2022-06-03 12:03 UTC, omarismail commented on CHANGELOG.md
> +* r/tfe_workspace: Default value of the `file_triggers_enabled` field is changed to `false`.
We should reference that `false` is the default value in the TFC API.

2022-06-03 12:04 UTC, omarismail approved these changes
two comments, otherwise lgtm. ping for another ✅

2022-06-03 13:04 UTC, sebasslash requested changes
Looks good 🔥 . Last thing would be to update the relevant provider documentation as well:

https://github.com/hashicorp/terraform-provider-tfe/blob/6f515c30a7cf5281addf417dd40fe730d9716ee5/website/docs/r/workspace.html.markdown?plain=1#L72-L75

2022-06-03 18:10 UTC, brandonc approved these changes

2022-06-07 07:56 UTC, matejrisek commented
> Looks good 🔥 . Last thing would be to update the relevant provider documentation as well:
> 
> https://github.com/hashicorp/terraform-provider-tfe/blob/6f515c30a7cf5281addf417dd40fe730d9716ee5/website/docs/r/workspace.html.markdown?plain=1#L72-L75

Good catch @sebasslash, addressed in 21d20d4c4145149701f3fb280657aedad235f2c2

2022-06-08 07:17 UTC, merged