Add workspace run task stage property
hashicorp/terraform-provider-tfe pull request #555
Opened 2022-07-19 09:25 UTC by glennsarti

## Description

_Describe why you're making this change._

_Remember to:_

- _Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/README.md#updating-the-changelog)_

- _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/README.md#updating-the-documentation)_

## Testing plan

1.  _Describe how to replicate_
1.  _the conditions_
1.  _under which your code performs its purpose,_
1.  _including example Terraform configs where necessary._

## External links

_Include any links here that might be helpful for people reviewing your PR. If there are none, feel free to delete this section._

- [go-tfe documentation](https://pkg.go.dev/github.com/hashicorp/go-tfe?tab=doc#xxxx)
- [API documentation](https://www.terraform.io/docs/cloud/api/xxxx.html)
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/xxxx)

## Output from acceptance tests

_Please run applicable acceptance tests locally and include the output here. See TESTS.md to learn how to run acceptance tests._

_If you are an external contributor, your contribution(s) will first be reviewed before running them against the project's CI pipeline._

```
$ TESTARGS="-run TestAccTFEWorkspace" make testacc

...
```

2022-08-15 02:21 UTC, cam-stitt approved these changes
Seems good to me. Would like someone from the CLI team to cover this also.

2022-08-17 06:28 UTC, glennsarti commented
Rebased due to changelog merge conflict

2022-08-17 16:14 UTC, brandonc requested changes
This looks great. The only problem is that we released 0.36.0 and now the CHANGELOG needs to be moved to a new ## Unreleased section.

I also would hesitate to merge this unless it was available to customers. Can it wait until GA or is there some reason to publish this early?

2022-08-18 02:03 UTC, glennsarti commented
> I  also would hesitate to merge this unless it was available to customers.

It is available in TFC for everyone, but are you worried about TFE?

2022-08-18 02:06 UTC, glennsarti commented
Fixed the changelog

2022-08-18 16:15 UTC, brandonc commented
@glennsarti nope- I didn't realize the flag had been enabled for customers.

2022-08-18 16:16 UTC, brandonc approved these changes

2022-08-18 16:16 UTC, merged