Add ForceUpdate to organization_membership_ids to resolve deletion order issue
hashicorp/terraform-provider-tfe pull request #657
Opened 2022-10-13 17:48 UTC by annawinkler

## Description

@brandonc found an order of deletion issue where we're removing an `tfe_organization_membership` before removing the relationship from the `tfe_team_organization_members` resource, causing a 500 from the API. 

This PR fixes that issue by forcing a recreation whenever `organization_membership_ids` is modified. By adding `ForceNew`, terraform is forced to update the relationships first before the `tfe_organization_membership` is deleted.

_Remember to:_

- _Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CONTRIBUTING.md#updating-the-changelog)_

- _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CONTRIBUTING.md#updating-the-documentation)_

## Testing plan

1. Here is a sample config you can use:

```
provider "tfe" {
...
}

resource "tfe_team" "test" {
  name         = "happy-team"
  organization = "hashicorp"
}

resource "tfe_organization_membership" "example1" {
  organization = "hashicorp"
  email = "example1@hashicorp.com"
}
resource "tfe_organization_membership" "example2" {
  organization = "hashicorp"
  email = "example2@hashicorp.com"
}

resource "tfe_organization_membership" "example3" {
  organization = "hashicorp"
  email = "example3@hashicorp.com"
}

resource "tfe_team_organization_members" "test" {
  team_id = tfe_team.test.id

  organization_membership_ids = [
    tfe_organization_membership.example1.id,
    tfe_organization_membership.example2.id
    tfe_organization_membership.example3.id
  ]
}
```

2. Run `terraform apply`
3. Remove `tfe_organization_membership` `example3` and rerun `terraform apply`
4. There was an error before, and with this change there isn't an error.

## External links

- [API documentation - Organization Memberships](https://www.terraform.io/cloud-docs/api-docs/organization-memberships)
- [API documentation - Team Membership](https://www.terraform.io/cloud-docs/api-docs/team-members)

## Output from acceptance tests

_Please run applicable acceptance tests locally and include the output here. See TESTS.md to learn how to run acceptance tests._

_If you are an external contributor, your contribution(s) will first be reviewed before running them against the project's CI pipeline._

```
$ TESTARGS="-run TestAccTFEWorkspace" make testacc

...
```

2022-10-13 18:01 UTC, brandonc requested changes
This seems a tad aggressive. The point of the resource is to allow bulk management of memberships and not allowing updates undermines that. What if we just assume that this particular error is ok when deleting a member and continue the update?

2022-10-13 18:02 UTC, annawinkler commented
> This seems a tad aggressive. The point of the resource is to allow bulk management of memberships and not allowing updates undermines that. What if we just assume that this particular error is ok when deleting a member and continue the update?

That sounds good. Will rework the PR.

2022-10-13 18:03 UTC, annawinkler commented
I'll close this PR and reopen a new one to be cleaner.

2022-10-13 18:05 UTC, brandonc commented
I see now that it's a single API call. So my last feedback isn't as poignant as I thought. We could check for existence of members prior to calling delete on them. Ill think more.

2022-10-13 18:07 UTC, annawinkler commented
> I'll close this PR and reopen a new one to be cleaner.

Actually, I'm going to wait until we can discuss further.

2022-10-18 19:16 UTC, brandonc commented
I think I prefer https://github.com/hashicorp/terraform-provider-tfe/pull/665

2022-10-18 19:16 UTC, closed without merging