multiple workspaces management example
hashicorp/terraform-provider-tfe pull request #774
Opened 2023-01-24 21:19 UTC by Uk1288

## Description

This PR show an example of using the tfe provider to manage multiple workspaces with associated workspace variables. 

 _[Origin PR](https://github.com/hashicorp/terraform-provider-tfe/pull/129)_

## Testing plan

1.  Run the workspaces example config in the PR

## External links

- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/129)

2023-01-24 21:22 UTC, laurenolivia approved these changes
awesome ✨

2023-01-25 16:46 UTC, sebasslash requested changes
[Non-blocking feedback] There are tons of different ways to write a configuration -- personally I find this example to be a tad bit convoluted surrounding how variables are populated for the managed workspaces, especially if the assumption here is the customer is starting out on managing cloud workspaces. I'm not particularly fond of having one giant map being the source of truth to provision variables for each workspace -- but again, personal bias. Also it's possible to get away with using one github repository for both manager/managed configurations and simply changing the working directory. 

[Blocking feedback] Bias aside, there are some really small blocking items down below :arrow_down: 

That said, this is great work! :rocket:

2023-01-25 16:46 UTC, sebasslash commented on examples/workspaces_variables/managed/main.tf
> +}
Are these supposed to be marked sensitive? Going of the `sens_` prefix.

2023-01-25 16:46 UTC, sebasslash commented on examples/workspaces_variables/managed/main.tf
> +}
Same here

2023-01-25 16:46 UTC, sebasslash commented on examples/workspaces_variables/managed/main.tf
> +  type = list
Should be `list(<type>)`, same goes for `variable "a_map"`

2023-01-25 16:46 UTC, sebasslash commented on examples/workspaces_variables/manager/main.tf
> +variable "additional_vars" {
These variables should specify their type. Given this is an example for those starting to manage TFC workspaces we should eliminate as many assumptions as we can.

2023-01-25 17:21 UTC, sebasslash commented
Mentioning @brenthc for visibility

2023-01-25 21:24 UTC, sebasslash approved these changes

2023-01-25 21:28 UTC, merged