Update documentation reference
hashicorp/terraform-provider-tfe pull request #878
Opened 2023-05-10 20:20 UTC by BrianMMcClain

## Description

Updated several documentation references to bring them in line with current doc standardization

2023-05-10 22:08 UTC, nfagerlund requested changes
One typo, but otherwise 👍🏼

2023-05-10 22:09 UTC, nfagerlund approved these changes

2023-05-10 22:35 UTC, brandonc reviewed
Question

2023-05-10 22:35 UTC, brandonc commented on website/docs/d/agent_pool.html.markdown
> +~> **NOTE:** This resource requires using the provider with [Terraform Cloud](https://www.hashicorp.com/products/terraform/pricing).
Arguably, all the resources require Terraform Cloud... One bit of lost information here is that agent pools require a Cloud Business plan. Is your intent to improve the link text (by omitting the word "here", for instance)? I might suggest

```suggestion
~> **NOTE:** This resource requires using the provider with a [Terraform Cloud Business(https://www.hashicorp.com/products/terraform/pricing) account.
```

2023-05-10 22:35 UTC, brandonc commented on website/docs/d/agent_pool.html.markdown
> +~> **NOTE:** This resource requires using the provider with [Terraform Cloud](https://www.hashicorp.com/products/terraform/pricing).
Arguably, all the resources require Terraform Cloud... One bit of lost information here is that agent pools require a Cloud Business plan. Is your intent to improve the link text (by omitting the word "here", for instance)? I might suggest

```suggestion
~> **NOTE:** This resource requires using the provider with a [Terraform Cloud Business(https://www.hashicorp.com/products/terraform/pricing) account.
```

2023-05-10 23:35 UTC, brandonc approved these changes

2023-05-11 19:02 UTC, nfagerlund commented
Ok, after talking in Slack we realized that agents have been working in TFE for YEARS, so closing this in favor of https://github.com/hashicorp/terraform-provider-tfe/pull/880

2023-05-11 19:02 UTC, closed without merging