Incorporate missing post plan terminal statuses to ensure plan is completely processed before attempting to confirm run
hashicorp/terraform-provider-tfe pull request #921
Opened 2023-06-06 14:39 UTC by Uk1288

## Description

_Describe why you're making this change._

_Remember to:_

- _Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md)_

- _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md#updating-the-documentation)_

## Testing plan

1.  _Describe how to replicate_
1.  _the conditions_
1.  _under which your code performs its purpose,_
1.  _including example Terraform configs where necessary._

## External links

_Include any links here that might be helpful for people reviewing your PR. If there are none, feel free to delete this section._

- [go-tfe documentation](https://pkg.go.dev/github.com/hashicorp/go-tfe?tab=doc#xxxx)
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs/xxxx)
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/xxxx)

## Output from acceptance tests

_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/testing.md) to learn how to run acceptance tests._

_If you are an external contributor, your contribution(s) will first be reviewed before running them against the project's CI pipeline._

```
$ TESTARGS="-run TestAccTFEWorkspace" make testacc

...
```

2023-06-07 18:18 UTC, brandonc commented on tfe/resource_tfe_workspace_run.go
> +	tfe.RunPrePlanRunning:    true,
With the exception of `RunPostPlanCompleted`, I don't understand how some of these can be terminal statuses, when they appear to be transition states... Can you elaborate?

2023-06-07 22:45 UTC, brandonc commented on tfe/workspace_run_helpers.go
In general, I find your diagnosis and fix to be convincing... but I'm also finding the helpers to be difficult to read and reason about and feel like we should take a moment to simplify them. I identified these specific things that could make this module simpler:

1. syntactically, I think there are two problems with awaitRun:
    a) nested switch statements-- I find it difficult to mentally retain a stack context once we reach that second nesting.
    b) this function takes a lot of arguments, which is an indicator that it could be doing too much or the input data is not related enough
2. mixed responsibilities: there are `interface{}` and provider-specific args in many helpers. Example: meta interface{} and schema.ResourceData args could be replaced with strong types like ConfiguredClient, retry/retry backoff integers, workspace ID, etc -- The idea would be that the helpers aren't interpreting provider schema or interfaces so that narrows the scope of their input.
3. the main entry point, createWorkspaceRun is looong so it may be best to try and break it into conceptual stages. I don't have a strong feeling about how to improve it, yet, but just moving code to subroutines that reflect the actual run stages might be a first step.

Does any of this resonate with you? What are your thoughts?

2023-06-14 15:07 UTC, Uk1288 commented on tfe/workspace_run_helpers.go
yes, this makes sense to me. I broke down the methods into smaller ones to represent action steps. The only one I have not updated is the double switch statement because the method is now smaller and straight forward. If we still want to get rid of that, I can replace it with an `if..else` statement. WDYT?

2023-06-14 16:25 UTC, Uk1288 commented
- [ ] TO-DO: upgrade go-tfe after changes are good to go.

2023-06-16 00:08 UTC, nfagerlund requested changes
This is getting there! I think you've split out the duties in a fairly legible way among these functions; some of the argument lists are still a bit unpleasant, but I think that's destiny, kind of, when the task is this annoying.

But I have some major concerns about mutating that top-scope `planPendingStatuses` map, and I don't think we should do it. I think what I'd suggest for a refactor goes something like this:

### The root issue:

- `isPlanComplete()` needs to inherently know about the list of plan terminal statuses.
- The call to `awaitRun()` needs to pass in the list of plan pending statuses.
- The actual lists of plan pending/terminal statuses depend on the run, _plus_ whether `hasPostPlanTaskStage` (which is inherent in the run but has to be discovered by making additional requests and then remembered for later, and we don't want those tightly-scoped helper funcs hitting the client.)

### What to do:

- Make a func that takes (run, hasPostPlanTaskStage) and returns a fresh planTerminalStatuses map.
- Make a func that takes (run, hasPostPlanTaskStage) and returns a fresh planPendingStatuses map.
- Make a func that takes planTerminalStatuses _and returns an anonymous function that can be used as an `isPlanComplete()` func._
- Then completely remove `hasPostPlanTaskStage` from the signatures of awaitRun and all the completion checker helper funcs, because `isPlanComplete` doesn't need it anymore -- it'll be a closure that already knows the things it currently needs `hasPostPlanTaskStage` in order to derive.

2023-06-26 17:05 UTC, Uk1288 commented on tfe/workspace_run_helpers.go
> +		planPendingStatuses[tfe.RunPlanned] = true
Right, mutating the global planPendingStatuses map raised questions for me as well, am glad that this comment validated my thought.

2023-06-26 22:10 UTC, nfagerlund commented
So these revisions look pretty great. Once the required extra status is merged into go-tfe and the provider can build properly, hit me up if I'm around and I'll try and do a smoke test; I think I still have a config sitting around from the last time we jammed on this.

2023-06-29 18:13 UTC, merged